trigger:
- master

pool: AG1-Pool

steps:

- script: |
    npm install snyk -g
    snyk -v
    terraform init
    terraform plan -out=tfplan
    terraform show --json tfplan > tfplan.json
    snyk iac test tfplan.json --report
    
